/*
 Copyright (c) 2013, Raonwiz Technology Inc. All rights reserved.
*/
window.DEXT5||(window.DEXT5=function(){return{isRelease:!0,isPopUpCssLoaded:!1,version:"DEXT5 Editor",ReleaseVer:"3.5.1058526.1800.01",ServerReleaseVer:"",cabVersion:"3,6,0,27",rootPath:function(){var b=window.DEXT5_ROOTPATH||"";if(!b)for(var c=document.getElementsByTagName("script"),a=c.length,e=null,g=0;g<a;g++){var e=c[g],k=e.src.match(/(^|.*[\\\/])dext5editor.js(?:\?.*)?$/i);"samsung.net"==document.domain&&(k=e.src.match(/(^|.*[\\\/])helloeditor.js(?:\?.*)?$/i));if(k){b=k[1];break}}-1==b.indexOf(":/")&&
(b=0===b.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+b:location.href.match(/^[^\?]*\/(?:)/)[0]+b);b=b.substring(0,b.length-1);b=b.substring(0,b.lastIndexOf("/"))+"/";if(!b)throw"DEXT5 Editor installation path could not be automatically detected.";return b}(),getUrl:function(b){-1==b.indexOf(":/")&&0!==b.indexOf("/")&&(b=this.rootPath+b);this.ReleaseVer&&"/"!=b.charAt(b.length-1)&&!/[&?]ver=/.test(b)&&(b+=(0<=b.indexOf("?")?"&":"?")+"ver="+this.ReleaseVer);return b},DEXTMULTIPLE:{},DEXTHOLDER:{},
ShowTextChangeAlert:!0}}(),DEXT5.brower||(DEXT5.browser=function(){var b=navigator.userAgent.toLowerCase(),c=window.opera,c={ie:-1<b.search("trident")||-1<b.search("msie")||-1<b.search("edge/12")?!0:!1,opera:!!c&&c.version,webkit:-1<b.indexOf(" applewebkit/"),mac:-1<b.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<b.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(b),isCustomDomain:function(){if(!this.ie)return!1;var a=document.domain,b=window.location.hostname;return a!=b&&
a!="["+b+"]"},isHttps:"https:"==location.protocol};c.gecko="Gecko"==navigator.product&&!c.webkit&&!c.opera;c.ie&&(c.gecko=!1);c.webkit&&(-1<b.indexOf("chrome")?(c.chrome=!0,-1<b.indexOf("opr")&&(c.opera=!0,c.chrome=!1)):c.safari=!0);var a;c.ieVersion=0;c.ie&&(a=c.quirks||!document.documentMode?-1<b.indexOf("msie")?parseFloat(b.match(/msie (\d+)/)[1]):-1<b.indexOf("trident")?parseFloat(b.match(/rv:([\d\.]+)/)[1]):-1<b.indexOf("edge/12")?12:7:document.documentMode,c.ieVersion=a,c.ie12=12==a,c.ie11=
11==a,c.ie10=10==a,c.ie9=9==a,c.ie8=8==a,c.ie7=7==a,c.ie6=7>a||c.quirks,-1<b.indexOf("trident")?c.trident=parseFloat(b.match(/ trident\/(\d+)/)[1]):c.trident="");c.gecko&&(a=b.match(/rv:([\d\.]+)/))&&(a=a[1].split("."),a=1E4*a[0]+100*(a[1]||0)+1*(a[2]||0));c.webkit&&(a=parseFloat(b.match(/ applewebkit\/(\d+)/)[1]));return c}()));
DEXT5.config={Width:"",Height:"",SkinName:"",InitXml:"",InitServerXml:"",ToSavePathURL:"",ToSaveFilePathURL:"",ServerDomain:"",HandlerUrl:"",InitVisible:!0,DefaultMessage:"",FirstLoadType:"",FirstLoadMessage:"",FileFieldID:"",EditorHolder:"",zTopMenu:"",zToolBar:"",zTopStatusBar:"",zStatusBar:"",zXssUse:"",zXssRemoveTags:"",zXssRemoveEvents:"",Mode:"",zIndex:"",NextTabElementId:"",IgnoreSameEditorName:"0",ChangeMultiValueMode:"",EditorBorder:"",InitLang:"",Lang:"",IconName:"icon",CustomCode:"",EnterTag:"",
userFontFamily:"",userFontSize:"",UserFieldID:"",UserFieldValue:"",LicenseKey:"",mimeCharset:"",mimeConentEncodingType:"",mimeFileTypeFilter:"",mimeLocalOnly:"",mimeRemoveHeader:"",userOpenDlgTitle:"",userOpenDlgType:"",userOpenDlgInitDir:"",userImageDlgStyle:"",mimeBaseURL:"",focusInitObjId:"",focusInitEditorObjId:"",tabIndexObjId:"",pluginUse:"",imageEditorUse:"",mimeUse:"",officeLineFix:"",useLog:"0",RootPath:"",EditorTabDisable:"",FormListUrl:"",RunTimes:"",MouseEventCancel:!1,KeyEventCancel:!1,
SetValueObjId:"",LoadedEvent:"",scrollOverflow:"",DocType:"",DevelopLangage:"",UnitDelimiter:"",UnitAttributeDelimiter:"",EditorBodyEditable:"",SymbolUrl:"",AccessibilityValidationItems:"",ViewModeAutoHeight:"",ViewModeAutoWidth:"",ShowDialogPosition:"",StatusBarItem:"",StatusBarInitMode:"",ImageBaseUrl:"",DragResize:"",DragResizeApplyBrowser:"",ReplaceOutsideImage:"",ReplaceOutsideImageExceptDomain:"",RemoveItem:"",RemoveContextItem:"",ManagerMode:"",EventList:"",TableLock:{Use:"",LockName:"",ShowLockIconUserMode:"",
TableLockMode:""},FontFamilyList:"",FontSizeList:"",LineHeightList:"",FormattingList:"",FrameFullScreen:"",DialogWindow:null,AdminTableLock:{DefaultShowLockIconUserMode:"",DefaultLockName:"",CheckLockName:"",DefaultTableLockMode:""},UserTableLock:{Use:"",LockName:"",DefaultTableLockMode:"",DefaultShowLockIcon:""},RemoveComment:"",SaveFolderNameRule:"",SaveFileFolderNameRule:"",ToolBarGrouping:"",SetDefaultValueInEmptyTag:"",LoadErrorCustomMessage:"",PhotoEditorId:"",ProductKey:"",LicenseKey:"",DirectEditHtmlUrl:"",
UserHelpUrl:"",UseGZip:"0",StatusBarLoading:"",TopStatusBarLoading:"",HandlerUrlSaveForNotes:"",HasContainer:"",Security:{EncryptParam:""}};
DEXT5.ajax=function(){var b=function(){if(!DEXT5.browser.ie||"file:"!=location.protocol){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return null},c=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},a=function(a){return c(a)?a.responseText:null},e=function(a){if(c(a)){var b=a.responseXML;return b?b:a.responseText}return null},
g=function(a,c,e){var d=!!c,g=b();if(!g)return null;g.open("GET",a,d);d&&(g.onreadystatechange=function(){4==g.readyState&&(c(e(g)),g=null)});try{g.send(null)}catch(l){return null}setTimeout(function(){g.abort()},5E3);return d?"":e(g)};return{load:function(b,c){return g(b,c,a)},loadXml:function(a,b){return g(a,b,e)},postData:function(a,c){var e;a:if(e=b()){try{e.open("POST",a,!1),e.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8"),e.send(c)}catch(d){e=null;break a}e=
e.responseText}else e=null;return e},postFileData:function(a,c){var e;a:if(e=b()){try{e.open("POST",a,!1);var d="--------------------"+(new Date).getTime();e.setRequestHeader("Content-Type","multipart/form-data; boundary="+d);for(var d="--"+d,g="",l=c.split("&"),q=l.length,r=null,t="",A="",x=0;x<q;x++)r=l[x].split("="),"imagedata"==r[0]?t=r[1]:(g+=d+"\r\n",g+='Content-Disposition: form-data; name="'+r[0]+'"\r\n\r\n',g+=r[1]+"\r\n");for(var l=null,q="",B=window.atob(t),H=B.length,l=new Uint8Array(new ArrayBuffer(H)),
x=0;x<H;x++)l[x]=B.charCodeAt(x),q+=String.fromCharCode(l[x]);String.fromCharCode.apply([],new Uint8Array(l));new Uint8Array(l);A=q;g+=d+"\r\n";g+='Content-Disposition: form-data; name="Filedata"; filename="'+(new Date).getTime()+'"\r\n';g+="Content-Type: image/png\r\n";g+="\r\n";g+=A+"\r\n";e.send(g+(d+"--\r\n"))}catch(T){e=null;break a}e=e.responseText}else e=null;return e}}}();
DEXT5.util={G_IMG_LIST:{},trim:function(b){return b.trim?b.trim():b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},setClass:function(b,c){b.className=c},getClass:function(b){return b.className},checkUrl:function(b){var c=!1;return c=(new RegExp(/(http|ftp|https|news):\/\/[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/)).test(b)},makeIframe:function(){var b;try{b=document.createElement('<iframe frameborder="0" >')}catch(c){b=document.createElement("iframe")}b.style.margin="0px";b.style.padding=
"0px";b.frameBorder=0;b.style.overflow="auto";b.style.overflowX="hidden";b.style.backgroundColor="#ffffff";return b},addEvent:function(b,c,a,e){b.addEventListener?b.addEventListener(c,a,e):b.attachEvent&&b.attachEvent("on"+c,a)},removeEvent:function(b,c,a,e){b.removeEventListener?b.removeEventListener(c,a,e):b.detachEvent&&b.detachEvent("on"+c,a)},stopEvent:function(b){"bubbles"in b?b.bubbles&&b.stopPropagation():b.cancelBubble=!0},cancelEvent:function(b){b.preventDefault?b.preventDefault():b.returnValue=
!1},ajax:{xml_http_request:function(){var b;window.XMLHttpRequest?b=new XMLHttpRequest:window.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));return b}},url:{full_url:function(b){var c="";if(0==b.indexOf("http://")||0==b.indexOf("https://"))c=b;else if(0==b.indexOf("/"))c=location.protocol+"//"+location.host+b;else var c=location.href,a=c.lastIndexOf("/"),c=c.substring(0,a+1),c=c+b;return c}},xml:{count:function(b,c){return b?b.getElementsByTagName(c).length:0},getNode:function(b,c){return null==
b||void 0==b?null:this.getNodeIdx(b,c,0)},getNodeIdx:function(b,c,a){return b.getElementsByTagName(c)[a]},getNodeValue:function(b,c){return null==b||void 0==b?"":this.getNodeValueIdx(b,c,0)},getNodeValueIdx:function(b,c,a){b=this.getNodeIdx(b,c,a);return this.getValue(b)},getValue:function(b){var c="",a="";if(void 0!=b)try{0<b.childNodes.length&&(a=c=b.firstChild.nodeValue);try{("product_key"==b.nodeName||"font"==b.nodeName||"encoding"==b.nodeName||"doctype"==b.nodeName)&&2<=b.childNodes.length&&
(c=b.textContent?b.textContent:a)}catch(e){c=a}}catch(g){c="parsing error"}return c}},htmlToLowerCase:function(b){if(8<DEXTTOP.DEXT5.browser.ieVersion&&0==DEXTTOP.DEXT5.browser.quirks)return b;var c=RegExp("<[^>]+>","g");results=b.match(c);if(null==results)return b;var a=c=-1,e=0,g=results.length;for(i=0;i<g;i++){original=results[i];c=original.indexOf("'");a=original.indexOf('"');e=2;1<c*a&&(-1<original.indexOf('="')?(results[i]=results[i].replace(/\'/g,"dext5_1q"),e=2):-1<original.indexOf("='")&&
(results[i]=results[i].replace(/\"/g,"dext5_2q"),e=1));stripquoted=1==e?results[i].replace(/ [^=]+= *\'[^\']*\'/g,""):results[i].replace(/ [^=]+= *"[^"]*"/g,"");c=RegExp(" [^=]+=[^ >]+","g");if(unquoted=stripquoted.match(c))for(c=unquoted.length,j=0;j<c;j++)addquotes=1==e?unquoted[j].replace(/( [^=]+=)([^ >]+)/g,"$1'$2'"):unquoted[j].replace(/( [^=]+=)([^ >]+)/g,'$1"$2"'),results[i]=results[i].replace(unquoted[j],addquotes);results[i]=results[i].replace(/<\/?[^>|^ ]+/,function(a){return a.toLowerCase()});
results[i]=1==e?results[i].replace(/ [^=|^ ]+=\'/g,function(a){return a.toLowerCase()}):results[i].replace(/ [^=|^ ]+="/g,function(a){return a.toLowerCase()});results[i]=results[i].replace(/dext5_1q/g,"'");results[i]=results[i].replace(/dext5_2q/g,'"');b=b.replace(original,results[i])}return b},hexDigits:"0123456789abcdef".split(""),hex:function(b){return isNaN(b)?"00":this.hexDigits[(b-b%16)/16]+this.hexDigits[b%16]},rgb2hex:function(b){b=b.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);if(!(null==b||
4>b.length))return"#"+this.hex(b[1])+this.hex(b[2])+this.hex(b[3])},dextSetAttribute:function(b,c,a,e){"string"==typeof a?0<a.length&&(b.style[c]=a+e):"number"==typeof a&&(b.style[c]=a)},getRealBackgoundImagePath:function(b){return b=b.replace(/url\(\s*(["']?)\s*([^\)]*)\s*\1\s*\)/i,function(b,a,e){return e})},replaceForXSS:function(b,c,a,e){var g=!1;try{if(""!=a)for(var k=a.split(","),f=k.length,h=0;h<f;h++){var d=k[h],m=new RegExp("<"+d+"[^>]*>[\\s\\S]*?</"+d+">","gim");1==m.test(b)&&(g=!0,b=b.replace(m,
""));var l=new RegExp("<"+d+"[^>]*>","gi");1==l.test(b)&&(g=!0,b=b.replace(l,""))}if(""!=e)for(var q=e.split(","),r=q.length,h=0;h<r;h++){var t=q[h],A=new RegExp("(?:"+t+')\\s*=\\s*"[^"]*"\\s*',"gi"),x=new RegExp("(?:"+t+")\\s*=\\s*'[^']*'\\s*","gi");if(A.test(b)||x.test(b))g=!0,b=b.replace(A,""),b=b.replace(x,"")}if(""!=c)for(var B=c.split(","),H=B.length,h=0;h<H;h++){var T=new RegExp("<\\/"+B[h]+">","gi"),U=b.match(new RegExp("<"+B[h]+"[^>]*>","gi"));if(U){var g=!0,X=U.length;c="";for(a=0;a<X;a++)c=
U[a].toLowerCase(),c=c.replace("<","&lt;"),c=c.replace(">","&gt;"),b=b.replace(U[a],c);b=b.replace(T,"&lt;/"+B[h]+"&gt;")}}}catch(Aa){}0==g&&(b="");return b},removeTags:function(b,c){if(""!=c)for(var a=c.split(","),e=null,g=a.length,k=0,f=0;f<g;f++)for(e=b.getElementsByTagName(a[f]),k=e.length,--k;0<=k;k--){var h=e[k];h.parentNode.removeChild(h)}},removeEvents:function(b,c,a){if(""!=c){b=c.split(",");c=a.length;for(var e=0,g=0;g<c;g++)for(var e=b.length,k=0;k<e;k++)a[g].removeAttribute(b[k])}},removeElement:function(b){for(;b.firstChild;)b.parentNode.insertBefore(b.firstChild,
b);b.parentNode.removeChild(b)},officeClean:function(b,c){if(""==b||void 0==b)return"";var a=null,e=[],a=!1;/([:| ])([-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)pt/gi.test(b)&&(a=!0);/([:| ])([:| ][-]{0,1}[0-9]+|[-]{0,1}[0-9]*[.]{1}[0-9]+)cm/gi.test(b)&&(a=!0);if(1==a){a=document.createElement("div");a.innerHTML=b;for(var e=a.getElementsByTagName("*"),g=e.length,k=0;k<g;k++){var f=e[k];if(f.style.width){var h=f.style.width.toLowerCase();-1<h.indexOf("pt")?(h=4*parseFloat(h)/3,0<h&&1>h&&(h=1),0>h&&(h=
0),h=Math.round(h)+"px",f.style.width=h):-1<h.indexOf("cm")&&(_cm=37.795275593333*parseFloat(h),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),h=Math.round(_cm)+"px",f.style.width=h)}f.style.height&&(h=f.style.height.toLowerCase(),-1<h.indexOf("pt")?(h=4*parseFloat(h)/3,0<h&&1>h&&(h=1),0>h&&(h=0),h=Math.round(h)+"px",f.style.height=h):-1<h.indexOf("cm")&&(_cm=37.795275593333*parseFloat(h),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),h=Math.round(_cm)+"px",f.style.height=h));h="";f.style.borderStyle&&(h=f.style.borderStyle);
""!=f.style.borderTop&&(f.style.borderTop=replacePtOrCmToPx(f.style.borderTop));""!=f.style.borderRight&&(f.style.borderRight=replacePtOrCmToPx(f.style.borderRight));""!=f.style.borderBottom&&(f.style.borderBottom=replacePtOrCmToPx(f.style.borderBottom));""!=f.style.borderLeft&&(f.style.borderLeft=replacePtOrCmToPx(f.style.borderLeft));""!=f.style.borderWidth&&(f.style.borderWidth=replacePtOrCmToPx(f.style.borderWidth));""!=h&&(f.style.borderStyle=h);try{if(-1<f.style.borderTop.indexOf("currentColor")){var d=
"",m="",l="",d=DEXT5.util.getStyle(f,"borderTopColor"),m=DEXT5.util.getStyle(f,"borderTopStyle"),l=DEXT5.util.getStyle(f,"borderTopWidth");f.style.borderTop=m+" "+l+" "+d}-1<f.style.borderRight.indexOf("currentColor")&&(l=m=d="",d=DEXT5.util.getStyle(f,"borderRightColor"),m=DEXT5.util.getStyle(f,"borderRightStyle"),l=DEXT5.util.getStyle(f,"borderRightWidth"),f.style.borderRight=m+" "+l+" "+d);-1<f.style.borderBottom.indexOf("currentColor")&&(l=m=d="",d=DEXT5.util.getStyle(f,"borderBottomColor"),m=
DEXT5.util.getStyle(f,"borderBottomStyle"),l=DEXT5.util.getStyle(f,"borderBottomWidth"),f.style.borderBottom=m+" "+l+" "+d);-1<f.style.borderLeft.indexOf("currentColor")&&(l=m=d="",d=DEXT5.util.getStyle(f,"borderLeftColor"),m=DEXT5.util.getStyle(f,"borderLeftStyle"),l=DEXT5.util.getStyle(f,"borderLeftWidth"),f.style.borderLeft=m+" "+l+" "+d)}catch(q){}}b=a.innerHTML}b=b.replace(/\.0px/g,"px");b=b.replace(/\t/g,"");b=DEXT5.util.removeOfficeDummyTag(b,"\x3c!--[if supportFields]>","<![endif]--\x3e");
a=RegExp("<o:p></o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p>\\s+</o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p ([^>]+)></o:p>","gi");b=b.replace(a,"");a=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");b=b.replace(a,"");b=b.replace(/\slang=[\"]?en-us[\"]?/gi,"");b=b.replace(/\sclass=[\"]?(mso)\w+[\"]?/gi,"");a=RegExp('mso-[^:]+:[^;">]+;',"gi");b=b.replace(a,"");a=RegExp('mso-[^:]+:[^;">]+("|\')',"gi");b=b.replace(a,"$1");b=DEXT5.util.replaceAll(b,"hairline","dotted");for(d=0;5>d;d++){e=["o:p","span","font"];
l=e.length;for(m=0;m<l;m++)a=new RegExp("<"+e[m]+"[^>]*></"+e[m]+">","gi"),b=b.replace(a,""),a=new RegExp("<"+e[m]+"[^>]*>&nbsp;</"+e[m]+">","gi"),b=b.replace(a,"&nbsp;"),"span"!=e[m]&&(a=new RegExp("<"+e[m]+"[^>]*> </"+e[m]+">","gi"),b=b.replace(a,"&nbsp;"));e=["o","v","w","m","x"];l=e.length;for(m=0;m<l;m++)0==m&&(b=b.replace(/<o:p/gi,"<dexto:p")),a=new RegExp("<"+e[m]+":[^/>]+/>","gi"),b=b.replace(a,""),a=new RegExp("<"+e[m]+":[^>]+>[^<]*</"+e[m]+":[^>]+>","gi"),b=b.replace(a,""),m==l-1&&(b=b.replace(/<dexto:p/gi,
"<o:p"))}b=b.replace(/style=""/gi,"");b=b.replace(/style=''/gi,"");b=b.replace(/\s>/gi,">");b=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(b);b=b.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");b=b.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");b=b.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");b=b.replace(/<\/th>&nbsp;<\/th>/g,"</th></th>");if(DEXTTOP.DEXT5.browser.ie&&10>DEXTTOP.DEXT5.browser.ieVersion){m=b.length;a=l=!1;k=g=e="";if(-1==b.indexOf("<")&&-1==b.indexOf(">"))for(d=0;d<m;d++)e=b.charAt(d),g=b.charAt(d+
1)," "!=e&&32!=e.charCodeAt(0)||" "!=g&&32!=g.charCodeAt(0)||(e="&nbsp;"),k+=e;else for(d=0;d<m;d++)e=b.charAt(d),g=b.charAt(d+1),"<"==e?(l=!1,a="p"==g.toLowerCase()?!0:!1):">"==e&&1==a?l=!0:1!=l||" "!=e&&32!=e.charCodeAt(0)||" "!=g&&32!=g.charCodeAt(0)||(e="&nbsp;"),k+=e;b=k}0==c&&(b=DEXTTOP.DEXT5.util.removeLocalFileImage(b));return b},removeLocalFileImage:function(b){if(""==b||void 0==b)return"";b=b.replace(/file:\/\/\//gi,"dext_local_file_image");reg_exp=RegExp("<img[^>]+dext_local_file_image[^>]+>",
"gi");return b=b.replace(reg_exp,"")},html2xhtml:function(b){if(""==b||void 0==b)return"";for(var c="area base br col embed frame hr img input link meta param".split(" "),a=c.length,e=null,g=RegExp(),k=0;k<a;k++)e=c[k],g=new RegExp("<"+e+" ([^>]*)>","gi"),b=b.replace(g,"<"+e+" $1 />"),g=new RegExp("<"+e+">","gi"),b=b.replace(g,"<"+e+" />");return b},emptyTagRemove:function(b){if(""==b||void 0==b)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var c=document.createElement("div");
c.innerHTML=b;for(var a=c.getElementsByTagName("p"),e=a.length,g,k,f="",h=[],d=["br","img","a","hr","table"],m=!1,l=0;l<e;l++)if(g=a[l],f="textContent"in g?g.textContent:g.innerText,""==f){k=g.innerHTML;for(var m=!1,q=d.length,r=0;r<q;r++)if(-1<k.toLowerCase().indexOf("<"+d[r])){m=!0;break}0==m&&h.push(g)}for(var t=h.length;0<t;)g=h.pop(),g.parentNode.removeChild(g);b=c.innerHTML}}catch(A){}return b},emptyTagRemoveCheckInContentTag:function(b,c){if(""==b||void 0==b)return"";try{if("1"==DEXTTOP.G_CURREDITOR._config.empty_tag_remove){var a=
document.createElement("div");a.innerHTML=b;for(var e=a.getElementsByTagName("p"),g=e.length,k,f,h="",d=[],m=!1,l=0;l<g;l++)if(k=e[l],h="textContent"in k?k.textContent:k.innerText,""==h){f=k.innerHTML;for(var m=!1,q=c.length,r=0;r<q;r++)if(-1<f.toLowerCase().indexOf("<"+c[r])){m=!0;break}0==m&&d.push(k)}for(var t=d.length;0<t;)k=d.pop(),a.removeChild(k);b=a.innerHTML}}catch(A){}return b},htmlRevision:function(b,c){if(""==b||void 0==b)return"";var a=null;"1"==DEXTTOP.G_CURREDITOR._config.removeComment&&
(b=b.replace(/\x3c!--[\w\s\d@{}:.;,'"%!#_=&|?~()[*+\/\-\]]*--\x3e/gi,""));DEXT5.browser.ie&&11>DEXT5.browser.ieVersion||c?(a=RegExp("><p><br></p></td>","gi"),b=b.replace(a,"><p>&nbsp;</p></td>")):(a=RegExp(">&nbsp;</td>","gi"),b=b.replace(a,"><p><br></p></td>"));for(var e=DEXTTOP.G_CURREDITOR._config.setDefaultValueInEmptyTag,g=e.length,k=0;k<g;k++){var f=e[k];DEXT5.browser.ie&&11>DEXT5.browser.ieVersion||c?(a=new RegExp("<"+f+"><br></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+
f+"><br/></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+"><br /></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+"></"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+">\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+">&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)><br></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)><br/></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">"),a=new RegExp("<"+
f+" ([^>]+)><br /></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)></"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">"),a=new RegExp("<"+f+" ([^>]+)>\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+" $1>&nbsp;</"+f+">")):(a=new RegExp("<"+f+"></"+f+">","gi"),b=b.replace(a,"<"+f+"><br></"+f+">"),a=new RegExp("<"+f+">&nbsp;</"+f+">","gi"),b=b.replace(a,"<"+f+"><br></"+f+">"),a=new RegExp("<"+f+">\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+"><br></"+f+">"),a=new RegExp("<"+
f+" ([^>]+)></"+f+">","gi"),b=b.replace(a,"<"+f+" $1><br></"+f+">"),a=new RegExp("<"+f+" ([^>]+)>&nbsp;</"+f+">","gi"),b=b.replace(a,"<p $1><br></p>"),a=new RegExp("<"+f+" ([^>]+)>\\s+</"+f+">","gi"),b=b.replace(a,"<"+f+" $1><br></"+f+">"))}if(0==DEXTTOP.DEXT5.browser.ie&&(a=b.match(RegExp("<([^>]*)>","igm"))))for(e=a.length,g="",k=0;k<e;k++)g=a[k].toString(),g=g.replace(/\r?\n|\r/g,""),b=b.replace(a[k],g);b=DEXTTOP.G_CURREDITOR._FRAMEWIN.ReplaceAll(b,"<c:foreach","<c:forEach");return b=DEXTTOP.G_CURREDITOR._FRAMEWIN.ReplaceAll(b,
"</c:foreach","</c:forEach")},nbspRemove:function(b){if(""==b||void 0==b)return"";var c=null,c=RegExp("<p>&nbsp;</p>","gi");b=b.replace(c,"<p></p>");c=RegExp("<p ([^>]+)>&nbsp;</p>","gi");return b=b.replace(c,"<p $1></p>")},ImageSrcConvert:function(b,c,a){var e=document.createElement("div");e.innerHTML=b;b=e.getElementsByTagName("img");var g=b.length,k=null,f="",h="";a+="_dext5_base64_image_";for(var d=0;d<g;d++)k=b[d],h=a+d,f=k.src,1==c?-1<f.indexOf("data:image")&&-1<f.indexOf("base64,")&&(this.G_IMG_LIST[h]=
f,k.src=h):-1<f.indexOf(a)&&(k.src=this.G_IMG_LIST[h],this.G_IMG_LIST[h]="");return b=e.innerHTML},getUrlString:function(b){b=DEXT5.util.replaceAll(b," ","%20");b=DEXT5.util.replaceAll(b,"&nbsp;","%21");b=DEXT5.util.replaceAll(b,"!","%20");b=DEXT5.util.replaceAll(b,'"',"%22");b=DEXT5.util.replaceAll(b,"#","%23");b=DEXT5.util.replaceAll(b,"$","%24");b=DEXT5.util.replaceAll(b,"%","%25");b=DEXT5.util.replaceAll(b,"&","%26");b=DEXT5.util.replaceAll(b,"'","%27");b=DEXT5.util.replaceAll(b,"+","%2B");b=
DEXT5.util.replaceAll(b,"/","%2F");b=DEXT5.util.replaceAll(b,":","%3A");b=DEXT5.util.replaceAll(b,";","%3B");b=DEXT5.util.replaceAll(b,"<","%3C");b=DEXT5.util.replaceAll(b,"=","%3D");b=DEXT5.util.replaceAll(b,">","%3E");b=DEXT5.util.replaceAll(b,"?","%3F");return b=DEXT5.util.replaceAll(b,"@","%40")},replaceAll:function(b,c,a){for(var e=b.indexOf(c);-1!=e;)b=b.replace(c,a),e=b.indexOf(c);return b},getSkinNames:function(){return"blue brown darkgray gold gray green orange pink purple red silver yellow".split(" ")},
CustomSetting:function(b,c,a){switch(b){case "function":CustomSettingFunction(a);break;case "remove_item":return CustomRemoveItem(c)}},replaceOneSpaceToNbsp:function(b){var c=b,a,e="";try{for(var g="span font a b strong i em strike u sup sub".split(" "),k=g.length,f=0;f<k;f++)for(var h=0;h<k;h++){e=c;a=new RegExp("<"+g[f]+" *([^>?+])*>(\\s+)</"+g[h]+">","gi");reg_exp2=new RegExp("</"+g[f]+">(\\s+)<"+g[h]+" *([^>?+])*>","gi");reg_exp3=new RegExp("<"+g[f]+" *([^>?+])*>(\\s+)<"+g[h]+">","gi");reg_exp4=
new RegExp("</"+g[f]+">(\\s+)</"+g[h]+" *([^>?+])*>","gi");try{var d=c.match(a);if(d)for(var m=d.length,l=0;l<m;l++)var q=d[l],r=/>\s+</.exec(q),t=r[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),q=q.replace(r,t),c=c.replace(d[l],q);if(d=c.match(reg_exp2))for(m=d.length,l=0;l<m;l++)q=d[l],r=/>\s+</.exec(q),t=r[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),q=q.replace(r,t),c=c.replace(d[l],q);if(d=c.match(reg_exp3))for(m=d.length,l=0;l<m;l++)q=d[l],r=/>\s+</.exec(q),t=r[0].replace(RegExp("\\s\\s",
"gi"),"&nbsp;&nbsp;"),q=q.replace(r,t),c=c.replace(d[l],q);if(d=c.match(reg_exp4))for(m=d.length,l=0;l<m;l++)q=d[l],r=/>\s+</.exec(q),t=r[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),q=q.replace(r,t),c=c.replace(d[l],q)}catch(A){c=e}}for(f=0;f<k;f++)for(h=0;h<k;h++)a=new RegExp("/"+g[f]+">\\s<"+g[h],"gi"),c=c.replace(a,"/"+g[f]+">&nbsp;<"+g[h]),a=new RegExp("/"+g[f]+">\\s\\n<"+g[h],"gi"),c=c.replace(a,"/"+g[f]+">&nbsp;<"+g[h]);return c}catch(x){return b}},parseIntOr0:function(b){b=parseInt(b,
10);return isNaN(b)?0:b},getUserLang:function(b){b=b.toLowerCase();var c="ko-kr";if(-1<b.indexOf("ko"))c="ko-kr";else if(-1<b.indexOf("en"))c="en-us";else if(-1<b.indexOf("ja"))c="ja-jp";else if(-1<b.indexOf("zh-cn")||0==b.indexOf("cn"))c="zh-cn";else if(-1<b.indexOf("zh-tw")||0==b.indexOf("tw"))c="zh-tw";return c},base64_encode:function(b){var c="",a,e,g,k,f,h,d=0;for(b=DEXT5.util.utf8_decode(b);d<b.length;)a=b.charCodeAt(d++),e=b.charCodeAt(d++),g=b.charCodeAt(d++),k=a>>2,a=(a&3)<<4|e>>4,f=(e&15)<<
2|g>>6,h=g&63,isNaN(e)?f=h=64:isNaN(g)&&(h=64),c=c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h);return c},base64_decode:function(b){var c="",a,e,g,k,f,h=0;for(b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");h<b.length;)a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),
e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(b.charAt(h++)),a=a<<2|e>>4,e=(e&15)<<4|k>>2,g=(k&3)<<6|f,c+=String.fromCharCode(a),64!=k&&(c+=String.fromCharCode(e)),64!=f&&(c+=String.fromCharCode(g));return c=DEXT5.util.utf8_decode(c)},makeEncryptParam:function(b){b=DEXT5.util.base64_encode(b);
b="R"+b;b=DEXT5.util.base64_encode(b);return b=b.replace(/[+]/g,"%2B")},utf8_decode:function(b){for(var c="",a=0,e=c1=c2=0;a<b.length;)e=b.charCodeAt(a),128>e?(c+=String.fromCharCode(e),a++):191<e&&224>e?(c2=b.charCodeAt(a+1),c+=String.fromCharCode((e&31)<<6|c2&63),a+=2):(c2=b.charCodeAt(a+1),c3=b.charCodeAt(a+2),c+=String.fromCharCode((e&15)<<12|(c2&63)<<6|c3&63),a+=3);return c},stringToXML:function(b){if(window.ActiveXObject){var c=new ActiveXObject("Microsoft.XMLDOM");c.async="false";c.loadXML(b)}else c=
(new DOMParser).parseFromString(b,"text/xml");return c},removeOfficeDummyTag:function(b,c,a){var e=b;try{for(var g=b.indexOf(c),k=b.indexOf(a);-1<g&&-1<k;)var f=e.substring(0,g),h=e.substring(k+a.length),e=f+h,g=e.indexOf(c),k=e.indexOf(a)}catch(d){e=b}return e},getStyle:function(b,c){var a;b.currentStyle?a=b.currentStyle:_iframeWin.getComputedStyle&&(a=_iframeWin.getComputedStyle(b,""));return a?a.getProperty?a.getProperty(c):a[c]:""}};
function DEXT_CONFIG(){""!=DEXT5.config.RootPath&&(DEXT5.rootPath=DEXT5.config.RootPath);this.defaultLineHeight=this.defaultFontFamily=this.defaultFontSize=this.lang=this.dext_path="";this.accessibility="0";this.visibility=!0;this.status_bar=this.top_status_bar=this.tool_bar=this.top_menu="0";this.toSaveFilePathURL=this.toSavePathURL="dext5editordata";this.saveFileFolderNameRule=this.saveFolderNameRule="YYYY/MM";this.serverDomain="";this.saveFileNameRule="GUID";this.showDialogPosition="1";this.image_convert_height=
this.image_convert_width=this.image_convert_format="";this.image_auto_fit="0";this.productKey="";this.imageEditorUse=this.plugInUse="0";this.fileFieldID=this.firstLoadMessage=this.firstLoadType=this.defaultMessage="";this.printPreview="0";this.basePrintFooter=this.basePrintHeader=this.printFooter=this.printHeader="";this.userCssUrl=this.sourceViewtype="0";this.nextTabElementId="";this.xhtml_value=this.empty_tag_remove=this.paste_image_base64="0";this.system_title="DEXT5";this.view_mode_auto_width=
this.view_mode_auto_height="0";this.changeMultiValueMode="doctype";this.tableAutoAdjust="1";this.trustSites="";this.contextMenuDisable="0";this.userFieldValue=this.userFieldID=this.enterTag="";this.mimeCharset="utf-8";this.mimeConentEncodingType="3";this.mimeLocalOnly=this.mimeFileTypeFilter="1";this.mimeRemoveHeader="0";this.imgDefaultMarginBottom=this.imgDefaultMarginTop=this.imgDefaultMarginRight=this.imgDefaultMarginLeft=this.imgDefaultHeight=this.imgDefaultWidth=this.mimeBaseURL=this.userImageDlgStyle=
this.userOpenDlgInitDir=this.userOpenDlgType=this.userOpenDlgTitle="";this.officeLineFix="1";this.useLog="0";this.EditorTabDisable="";this.unitDelimiter="\f";this.unitAttributeDelimiter="\x0B";this.style={skinName:"blue",width:"100%",height:"600px",InitVisible:!0,isFontSizeUse:!0,defaultMinHeight:"300px",iconName:"icon"};this.webPath={image:DEXT5.rootPath+"images/editor/",page:DEXT5.rootPath+"pages/",js:DEXT5.rootPath+"js/",js_dev:DEXT5.rootPath+"js_dev/",css:DEXT5.rootPath+"css/",css_dev:DEXT5.rootPath+
"css_dev/",include:DEXT5.rootPath+"include/",config:DEXT5.rootPath+"config/",help:DEXT5.rootPath+"help/"};this.holderID="";this.config_url=DEXT5.rootPath+"config/dext_editor.xml";this.emoticon_url=DEXT5.rootPath+"config/dext_emoticon.xml";this.forms_url=DEXT5.rootPath+"config/dext_formlist.xml";this.post_url=DEXT5.rootPath+"handler/upload_handler.ashx";this.proxy_url=this.post_url_save_for_notes="";this.plugin_root=DEXT5.rootPath+"plugin/";this.plugin_version=DEXT5.cabVersion;this.editor_url=DEXT5.isRelease?
DEXT5.rootPath+"pages/editor_release.html":DEXT5.rootPath+"pages/editor.html";this.pages={find:"editor_find.html",replace:"editor_replace.html",image:"editor_image.html",horizontal_line:"editor_horizontal_line.html",bg_image:"dext_bg_image.html",doc_bg_img:"editor_doc_bg_img.html",flash:"editor_flash.html",media:"editor_media.html",table:"editor_table.html",table_property:"editor_table_property.html",cell_property:"editor_cell_property.html",insert_row_column:"editor_insert_row_column.html",row_property:"editor_row_property.html",
column_property:"editor_column_property.html",emoticon:"editor_emoticon.html",bookmark:"editor_bookmark.html",iframe:"editor_iframe.html",hyperlink:"editor_hyperlink.html",split_cell:"editor_split_cell.html",about:"editor_about.html",symbol:"editor_symbol.html",setting:"editor_setting.html",template:"editor_template.html",tool_replace:"editor_tool_replace.html",insert_link_media:"editor_insert_link_media.html",m_image:"editor_m_image.html",m_emoticon:"editor_m_emoticon.html",cell_border:"editor_cell_border.html",
paste_dialog:"editor_paste.html",shortcut:"editor_shortcut.html",layout:"editor_layout.html",insert_file:"editor_insert_file.html",file_open:"editor_file_open.html",blockquote:"editor_blockquote.html",input_text:"editor_input_text.html",input_radio:"editor_input_radio.html",input_checkbox:"editor_input_checkbox.html",input_button:"editor_input_button.html",input_hidden:"editor_input_hidden.html",input_textarea:"editor_input_textarea.html",input_select:"editor_input_select.html",input_image:"editor_input_image.html",
accessibility_validation:"editor_accessibility_validation.html",table_lock_property:"editor_table_lock_property.html"};this.editor_id=this.xss_use=this.xss_remove_events=this.xss_remove_tags=this.replace_tagname="";this.mode="edit";this.mimeUse="0";this.zIndex=1E4;this.ruler={use:"0",view:"0",rulerInitPosition:"0",viewPointer:"1",viewGuideLine:"1",viewRuler:"1"};this.horizontalLine={use:"0",url:""};this.editorborder="1";this.imageBaseUrl=this.custom_code="";this.allowMediaFileType=[];this.allowImageFileType=
[];this.allowFlashFileType=[];this.allowInsertFileType=[];this.attachFileImage="1";this.tableClassList=[];this.tableLineStyleList=[];this.tableDefaultTdHeight=this.tableDefaultClass=this.tableDefaultHeight=this.tableDefaultWidth="";this.tableLineStyleValue={};this.tableLineStyleValue._solid="border-top: 1px solid #5d5d5d;";this.tableLineStyleValue._dotted="border-top: 1px dotted #5d5d5d;";this.tableLineStyleValue._dashed="border-top: 1px dashed #5d5d5d;";this.tableLineStyleValue._double="border-top: 3px double #5d5d5d;";
this.tableLineStyleValue._groove="border: 3px groove #e1e1e1;";this.tableLineStyleValue._ridge="border: 3px ridge #e1e1e1;";this.tableLineStyleValue._inset="border: 3px inset #e1e1e1;";this.tableLineStyleValue._outset="border: 3px outset #e1e1e1;";this.tableLineStyleValue._none="border: 1px none #5d5d5d;";this.tableLineStyleValue._hidden="border: 1px none #5d5d5d;";this.tableDefaultInoutdent=20;this.tableNoSelectionClass=this.tableNoActionClass=this.tableNoResizeClass=this.tableInitInoutdent="";this.tableColMaxCount=
this.tableRowMaxCount="13";this.allowInoutdentText="0";this.defaultBorderColor="#000000";this.showLineForBorderNone="0";this.tabIndexObjId=this.focusInitEditorObjId=this.focusInitObjId="";this.setDefaultStyle={value:"0",body_id:"dext_body",dext_set_style:"1"};this.setDefaultUserStyle=[];this.popupCssUrl="../css/editor_popup.css";this.symbolUrl="../js/editor_symbol.js";this.dialogJSUrl="../js/editor_dialog.js";this.customEventCmd={image:{ondbclick:""}};this.ieCompatible="";this.autoUrlDetect="1";this.scrollOverflow=
this.pasteRemoveEmptyTag="0";this.disableKeydown=this.autoBodyFit=this.disableTabletap=this.defaultImemode="";this.dragAndDropAllow="0";this.limitPasteHtmlLength={value:"0",length:13E5};this.pasteToImage="1";this.eventForPasteImage=this.notRepairInViewMode=this.viewModeAllowCopy=this.viewModeBrowserMenu=this.removeSpaceInTagname=this.wrapPtagToSource="0";this.useHtmlCorrection=this.removeColgroup="1";this.runtimes="";this.setAutoSave={mode:"2",interval:.5};this.insertCarriageReturn="0";this.returnEvent=
{mouse_event:"0",key_event:"0"};this.useCorrectInOutdent="0";this.isLoadedEditor=!1;this.setValueObjId="";this.replaceEmptyTagWithSpace="1";this.LoadedEvent="";this.frameFullScreen="0";this.currFontFamily="";this.allowImgSize="1";this.hyperlinkTargetList=[];this.hyperlinkCategoryList=[];this.hyperlinkProtocolList=[];this.developLang="NET";this.formMode="0";this.openDocument={beforeOpenEvent:"0",useHwp:"0",word:{maxSize:0,maxPage:0},excel:{maxSize:0,maxSheet:0},powerpoint:{maxSize:0,maxSlide:0}};this.removeLastBrTag=
"0";this.editorBodyEditable=!0;this.inoutdentDefaultSize=40;this.statusBarItem=this.accessibilityValidationItems="";this.statusBarInitMode="design";this.dragResize="0";this.dragResizeApplyBrowser=[];this.replaceOutsideImage={use:"0",exceptDomain:[]};this.eventList=[];this.userJsUrl="";this.fontFamilyList=[];this.fontSizeList=[];this.lineHeightList=[];this.formattingList=[];this.adminTableLock={defaultShowLockIconUserMode:"0",defaultLockName:"dext_lock",checkLockName:["dext_lock"],defaultTableLockMode:"2"};
this.userTableLock={use:"0",lockName:["dext_lock"],defaultTableLockMode:"2",defaultShowLockIcon:"1"};this.removeComment="1";this.tool_bar_grouping="0";this.setDefaultValueInEmptyTag=["p","div"];this.userHelpUrl=this.metaHttpEquiv=this.directEditHtmlUrl=this.userCssAlwaysSet=this.photoEditorId="";this.useGZip="0";this.topStatusBarLoading=this.statusBarLoading="1";this.hasContainer="0";this.security={encryptParam:"0"}}
function isExistEditorName(b){if(void 0==b||""==b)return 1;var c=DEXT5.DEXTMULTIPLE["dext_frame_"+b];return void 0==c||null==c?0:""!=DEXT5.config.EditorHolder&&DEXT5.DEXTHOLDER[b]==DEXT5.config.EditorHolder?3:2}function getNewNextEditorName(b){var c="",c=b.split("_"),a=c.length;1<a&&(b=b.replace("_"+c[a-1],""));c=b+getNextEditorNumber();0<isExistEditorName(c)&&(c=getNewNextEditorName(c));return c}var getNextEditorNumber=function(){var b=0;return function(){return"_"+ ++b}}();
function Dext5editor(b){var c=isExistEditorName(b);if(1==c)alert("editor's name is empty. Please, check editor's name");else{if(2==c)if("1"==DEXT5.config.IgnoreSameEditorName)b=getNewNextEditorName(b);else{alert("editor's name is already exist. Please, check editor's name");return}var a=new DEXT_CONFIG;if(0<DEXT5.config.InitServerXml.length)if(-1<DEXT5.config.InitServerXml.indexOf("f="))a.config_url=DEXT5.config.InitServerXml+"&dext5CMD=configRequest";else{alert("Error occurred reading the Editor Settings");
return}else 0<DEXT5.config.InitXml.length&&(0==DEXT5.config.InitXml.indexOf("http")?a.config_url=DEXT5.config.InitXml:a.config_url=DEXT5.rootPath+"config/"+DEXT5.config.InitXml);-1<a.config_url.indexOf("?")?a.config_url+="&t="+(new Date).getTime():a.config_url+="?t="+(new Date).getTime();var e=null,e=0<DEXT5.config.InitServerXml.length?DEXT5.ajax.load(a.config_url):DEXT5.ajax.loadXml(a.config_url);if(null==e)alert("ErrCode : 1000");else{if("object"!=typeof e)if(0==e.indexOf("[OK]"))e=e.substring(4),
e=DEXT5.util.base64_decode(e),e=e.substring(e.indexOf("<?")),e=DEXT5.util.stringToXML(e);else if(0==e.indexOf("[FAIL]")){alert("Error occurred reading the Editor Settings");return}this.configXml=e;3!=c&&(DEXT5.DEXTMULTIPLE["dext_frame_"+b]=b,DEXT5.DEXTHOLDER[b]=DEXT5.config.EditorHolder);DEXT5.isRelease?(a.popupCssUrl="../css/editor_popup.css",a.dialogJSUrl="../js/editor_dialog.js"):(a.popupCssUrl="../css_dev/editor_popup.css",a.dialogJSUrl="../js_dev/editor_dialog.js");var g=DEXT5.util.xml.getNode(e,
"xss_protection"),k=DEXT5.util.xml.getNodeValue(g,"xss_use"),f=DEXT5.util.xml.getNodeValue(g,"xss_remove_tags"),h=DEXT5.util.xml.getNodeValue(g,"xss_remove_events");""==k&&(k="0");""!=DEXT5.config.zXssUse&&(k=DEXT5.config.zXssUse);a.xss_use=k;""!=DEXT5.config.zXssRemoveTags&&(f=DEXT5.config.zXssRemoveTags);a.xss_remove_tags=f.toLowerCase();""!=DEXT5.config.zXssRemoveEvents&&(h=DEXT5.config.zXssRemoveEvents);"all"==h.toLowerCase()?a.xss_remove_events="onabort,onactivate,onafterprint,onafterupdate,onbeforeactivate,onbeforecopy,onbeforecut,onbeforedeactivate,onbeforeeditfocus,onbeforepaste,onbeforeprint,onbeforeunload,onbeforeupdate,onbegin,onblur,onbounce,oncellchange,onchange,onclick,oncontentready,oncontentsave,oncontextmenu,oncontrolselect,oncopy,oncut,ondataavailable, ondatasetchanged, ondatasetcomplete, ondblclick, ondeactivate,ondetach, ondocumentready, ondrag, ondragdrop, ondragend,ondragenter,ondragleave,ondragover,ondragstart,ondrop,onend,onerror,onerrorupdate,onfilterchange,onfinish,onfocus,onfocusin,onfocusout,onhelp,onhide,onkeydown,onkeypress,onkeyup,onlayoutcomplete,onload,onlosecapture,onmediacomplete,onmediaerror,onmedialoadfailed,onmousedown,onmouseenter,onmouseleave,onmousemove,onmouseout,onmouseover,onmouseup,onmousewheel,onmove,onmoveend,onmovestart,onopenstatechange,onoutofsync,onpaste,onpause,onplaystatechange,onpropertychange,onreadystatechange,onrepeat,onreset,onresize,onresizeend,onresizestart,onresume,onreverse,onrowclick,onrowenter,onrowexit,onrowout,onrowover,onrowsdelete,onrowsinserted,onsave,onscroll,onseek,onselect,onselectionchange,onselectstart,onshow,onstart,onstop,onsubmit,onsyncrestored,ontimeerror,ontrackchange,onunload,onurlflip":
a.xss_remove_events=h.toLowerCase();1E4<=parseInt(DEXT5.config.zIndex,10)&&(a.zIndex=parseInt(DEXT5.config.zIndex,10));a.editorborder=""==DEXT5.config.EditorBorder?"1":DEXT5.config.EditorBorder;var d=DEXT5.util.xml.getNode(e,"setting"),m=DEXT5.util.xml.getNodeValue(d,"runtimes"),l=DEXT5.util.xml.getNodeValue(d,"width"),q=DEXT5.util.xml.getNodeValue(d,"height"),r=DEXT5.util.xml.getNodeValue(d,"skinname"),t=DEXT5.util.xml.getNodeValue(d,"lang"),A=DEXT5.util.xml.getNodeValue(d,"accessibility"),x=DEXT5.util.xml.getNodeValue(d,
"showdialog_pos"),B=DEXT5.util.xml.getNodeValue(d,"source_viewtype"),H=DEXT5.util.xml.getNodeValue(d,"user_css_url"),T=DEXT5.util.xml.getNodeValue(d,"user_js_url"),U=DEXT5.util.xml.getNodeValue(d,"xhtml_value"),X=DEXT5.util.xml.getNodeValue(d,"system_title"),Aa=DEXT5.util.xml.getNodeValue(d,"table_auto_adjust"),Jb=DEXT5.util.xml.getNodeValue(d,"context_menu_disable"),V=DEXT5.util.xml.getNodeValue(d,"enter_tag"),Ba=DEXT5.util.xml.getNodeValue(d,"office_linefix"),Ca=DEXT5.util.xml.getNodeValue(d,"editor_tab_disable"),
Da=DEXT5.util.xml.getNodeValue(d,"frame_fullscreen"),Kb=DEXT5.util.xml.getNodeValue(d,"allow_img_size"),ia=DEXT5.util.xml.getNode(d,"user_css_url");"0"==Kb&&(a.allowImgSize="0");""!=DEXT5.config.FrameFullScreen?a.frameFullScreen=DEXT5.config.FrameFullScreen:""!=Da&&(a.frameFullScreen=Da);var ja="";""!=DEXT5.config.RunTimes?ja=DEXT5.config.RunTimes:""!=m&&(ja=m);a.runtimes=GetUserRunTimeEditor(ja);a.EditorTabDisable=""==DEXT5.config.EditorTabDisable?0==Ca.length?a.EditorTabDisable:Ca:DEXT5.config.EditorTabDisable;
a.contextMenuDisable="1"==Jb?"1":"0";var Ea=DEXT5.util.xml.getNodeValue(d,"ie_compatible");""!=Ea&&(a.ieCompatible=Ea);var Fa=DEXT5.util.xml.getNodeValue(d,"auto_url_detect");""!=Fa&&(a.autoUrlDetect=Fa);a.officeLineFix=""==DEXT5.config.officeLineFix?0==Ba.length?a.officeLineFix:Ba:DEXT5.config.officeLineFix;"1"==DEXT5.util.xml.getNodeValue(d,"paste_remove_empty_tag")&&(a.pasteRemoveEmptyTag="1");var Ga=DEXT5.util.xml.getNodeValue(d,"scroll_overflow");a.scrollOverflow=""==DEXT5.config.scrollOverflow?
0==Ga.length?a.scrollOverflow:Ga:DEXT5.config.scrollOverflow;"1"==DEXT5.util.xml.getNodeValue(d,"default_imemode")&&(a.defaultImemode="1");"1"==DEXT5.util.xml.getNodeValue(d,"disable_tabletap")&&(a.disableTabletap="1");"1"==DEXT5.util.xml.getNodeValue(d,"auto_body_fit")&&(a.autoBodyFit="1");"1"==DEXT5.util.xml.getNodeValue(d,"disable_keydown")&&(a.disableKeydown="1");var Lb=DEXT5.util.xml.getNode(d,"custom_event"),Mb=DEXT5.util.xml.getNode(Lb,"image"),Ha=DEXT5.util.xml.getNodeValue(Mb,"ondbclick");
""!=Ha&&(a.customEventCmd.image.ondbclick=Ha);var Nb=DEXT5.util.xml.getNode(d,"pageurl"),Ob=DEXT5.util.xml.getNode(Nb,"script"),Ia=DEXT5.util.xml.getNodeValue(Ob,"symbol");a.symbolUrl=""==DEXT5.config.SymbolUrl?""!=Ia?Ia:DEXT5.isRelease?"../js/editor_symbol.js":"../js_dev/editor_symbol.js":DEXT5.config.SymbolUrl;var ka=DEXT5.util.xml.getNodeValue(d,"icon_name");""!=ka&&(a.style.iconName=ka,DEXT5.config.IconName=ka);if(""==DEXT5.config.ImageBaseUrl){var Ja=DEXT5.util.xml.getNodeValue(d,"image_base_url");
""!=Ja&&(a.imageBaseUrl=Ja)}else a.imageBaseUrl=DEXT5.config.ImageBaseUrl;if(""==DEXT5.config.DragResize){var Ka=DEXT5.util.xml.getNodeValue(d,"drag_resize");""!=Ka&&(a.dragResize=Ka)}else a.dragResize=DEXT5.config.DragResize;if(""==DEXT5.config.DragResizeApplyBrowser){var ca=DEXT5.util.xml.getNode(d,"drag_resize");ca&&ca.getAttribute("apply_browser")&&""!=ca.getAttribute("apply_browser")&&(a.dragResizeApplyBrowser=ca.getAttribute("apply_browser").split(","))}else a.dragResizeApplyBrowser=DEXT5.config.DragResizeApplyBrowser.split(",");
""!=DEXT5.config.FontFamilyList&&(a.fontFamilyList=DEXT5.config.FontFamilyList.split(","));""!=DEXT5.config.FontSizeList&&(a.fontSizeList=a.fontSizeList.concat(DEXT5.config.FontSizeList.split(",")));""!=DEXT5.config.LineHeightList&&(a.lineHeightList.push(""),a.lineHeightList=a.lineHeightList.concat(DEXT5.config.LineHeightList.split(",")));""!=DEXT5.config.FormattingList&&(a.formattingList.push(""),a.formattingList=a.formattingList.concat(DEXT5.config.FormattingList.split(",")));if("1"==DEXT5.util.xml.getNodeValue(d,
"use_ruler")){a.ruler.use="1";a.ruler.view="1";var E=DEXT5.util.xml.getNode(d,"use_ruler");E.getAttribute("ruler_init_position")&&""!=E.getAttribute("ruler_init_position")&&(a.ruler.rulerInitPosition=E.getAttribute("ruler_init_position"));E.getAttribute("view_pointer")&&"1"!=E.getAttribute("view_pointer")&&(a.ruler.viewPointer="0");E.getAttribute("view_guide_line")&&"1"!=E.getAttribute("view_guide_line")&&(a.ruler.viewGuideLine="0");E.getAttribute("view_ruler")&&"1"!=E.getAttribute("view_ruler")&&
(a.ruler.viewRuler="0")}if("1"==DEXT5.util.xml.getNodeValue(d,"use_horizontal_line")){var la=DEXT5.util.xml.getNode(d,"use_horizontal_line");la.getAttribute("url")&&""!=la.getAttribute("url")&&(a.horizontalLine.use="1",a.horizontalLine.url=la.getAttribute("url"))}if(""==a.enterTag)if(""!=DEXT5.config.EnterTag){if(DEXT5.config.EnterTag=DEXT5.config.EnterTag.toLocaleLowerCase(),"br"==DEXT5.config.EnterTag||"div"==DEXT5.config.EnterTag)a.enterTag=DEXT5.config.EnterTag}else{if(V=V.toLocaleLowerCase(),
"br"==V||"div"==V)a.enterTag=V}else a.enterTag=a.enterTag.toLocaleLowerCase(),a.enterTag="br"!=a.enterTag&&"div"!=a.enterTag?"":V;var ma=DEXT5.util.xml.getNodeValue(d,"set_default_style"),F=DEXT5.util.xml.getNode(d,"set_default_style");""!=ma&&"0"!=ma?(a.setDefaultStyle.value=ma,""!=F.getAttribute("body_id")&&(a.setDefaultStyle.body_id=F.getAttribute("body_id")),F.getAttribute("user_style")&&""!=F.getAttribute("user_style")&&(a.setDefaultUserStyle=F.getAttribute("user_style").split(","))):F&&F.getAttribute("dext_set_style")&&
""!=F.getAttribute("dext_set_style")&&(a.setDefaultStyle.dext_set_style=F.getAttribute("dext_set_style"));var La=DEXT5.util.xml.getNodeValue(d,"drag_and_drop_allow");"1"==La&&(a.dragAndDropAllow=La);if("1"==DEXT5.util.xml.getNodeValue(d,"limit_paste_html_length")){a.limitPasteHtmlLength.value="1";var Ma=DEXT5.util.xml.getNode(d,"limit_paste_html_length");""!=Ma.getAttribute("length")&&(a.limitPasteHtmlLength.length=parseInt(Ma.getAttribute("length"),10))}"1"==DEXT5.util.xml.getNodeValue(d,"wrap_ptag_to_source")&&
(a.wrapPtagToSource="1");var na=DEXT5.util.xml.getNodeValue(d,"paste_to_image");if("0"==na||"2"==na)a.pasteToImage=na;"1"==DEXT5.util.xml.getNodeValue(d,"remove_space_in_tagname")&&(a.removeSpaceInTagname="1");"1"==DEXT5.util.xml.getNodeValue(d,"view_mode_browser_menu")&&(a.viewModeBrowserMenu="1");"1"==DEXT5.util.xml.getNodeValue(d,"view_mode_allow_copy")&&(a.viewModeAllowCopy="1");"1"==DEXT5.util.xml.getNodeValue(d,"event_for_paste_image")&&(a.eventForPasteImage="1");"0"==DEXT5.util.xml.getNodeValue(d,
"remove_colgroup")&&(a.removeColgroup="0");"0"==DEXT5.util.xml.getNodeValue(d,"use_html_correction")&&(a.useHtmlCorrection="0");var Na=DEXT5.util.xml.getNodeValue(d,"formlist_url");""!=DEXT5.config.FormListUrl?a.forms_url=DEXT5.config.FormListUrl:""!=Na&&(a.forms_url=Na);var oa=DEXT5.util.xml.getNodeValue(d,"set_auto_save");if(""!=oa&&(a.setAutoSave.mode=oa,"1"==oa&&(xmlSetAutoSaveNode=DEXT5.util.xml.getNode(d,"set_auto_save"),xmlSetAutoSaveNode.getAttribute("interval")&&""!=xmlSetAutoSaveNode.getAttribute("interval")))){var pa;
pa=Math.floor(10*xmlSetAutoSaveNode.getAttribute("interval"))/10;.5<=pa&&(a.setAutoSave.interval=pa)}"1"==DEXT5.util.xml.getNodeValue(d,"insert_carriage_return")&&(a.insertCarriageReturn="1");var Y=DEXT5.util.xml.getNode(d,"return_event");Y&&(Y.getAttribute("mouse_event")&&"1"==Y.getAttribute("mouse_event")&&(a.returnEvent.mouse_event="1"),Y.getAttribute("keyboard_event")&&"1"==Y.getAttribute("keyboard_event")&&(a.returnEvent.key_event="1"));"1"==DEXT5.util.xml.getNodeValue(d,"use_correct_in_outdent")&&
(a.useCorrectInOutdent="1");"0"==DEXT5.util.xml.getNodeValue(d,"replace_empty_tag_with_space")&&(a.replaceEmptyTagWithSpace="0");var I=DEXT5.util.xml.getNode(d,"manager_mode");""!=DEXT5.config.ManagerMode?a.formMode=DEXT5.config.ManagerMode:I&&I.getAttribute("use")&&"1"==I.getAttribute("use")&&(a.formMode=I.getAttribute("use"));if("1"==a.formMode&&""!=DEXT5.config.EventList)a.eventList=DEXT5.config.EventList.split(",");else if(I&&"1"==a.formMode)for(var Oa=DEXT5.util.xml.getNode(I,"event_list"),Pb=
DEXT5.util.xml.count(Oa,"event"),n=0;n<Pb;n++)a.eventList[n]=DEXT5.util.xml.getNodeValueIdx(Oa,"event",n);if(""!=DEXT5.config.AdminTableLock.DefaultShowLockIconUserMode||DEXT5.config.AdminTableLock.DefaultLockName||""!=DEXT5.config.AdminTableLock.CheckLockName||""!=DEXT5.config.AdminTableLock.DefaultTableLockMode)""!=DEXT5.config.AdminTableLock.DefaultShowLockIconUserMode&&(a.adminTableLock.defaultShowLockIconUserMode=DEXT5.config.AdminTableLock.DefaultShowLockIconUserMode),""!=DEXT5.config.AdminTableLock.DefaultLockName&&
(a.adminTableLock.defaultLockName=DEXT5.config.AdminTableLock.DefaultLockName),""!=DEXT5.config.AdminTableLock.CheckLockName&&(a.adminTableLock.checkLockName=DEXT5.config.AdminTableLock.CheckLockName.split(",")),""!=DEXT5.config.AdminTableLock.DefaultTableLockMode&&(a.adminTableLock.defaultTableLockMode=DEXT5.config.AdminTableLock.DefaultTableLockMode);else if(I){var w=DEXT5.util.xml.getNode(I,"table_lock");w&&(w&&w.getAttribute("default_show_lock_icon_user_mode")&&""!=w.getAttribute("default_show_lock_icon_user_mode")&&
(a.adminTableLock.defaultShowLockIconUserMode=w.getAttribute("default_show_lock_icon_user_mode")),w&&w.getAttribute("default_lock_name")&&""!=w.getAttribute("default_lock_name")&&(a.adminTableLock.defaultLockName=w.getAttribute("default_lock_name")),w&&w.getAttribute("check_lock_name")&&""!=w.getAttribute("check_lock_name")&&(a.adminTableLock.checkLockName=w.getAttribute("check_lock_name").split(",")),w&&w.getAttribute("default_table_lock_mode")&&""!=w.getAttribute("default_table_lock_mode")&&(a.adminTableLock.defaultTableLockMode=
w.getAttribute("default_table_lock_mode")))}if(""!=DEXT5.config.UserTableLock.Use)a.userTableLock.use=DEXT5.config.UserTableLock.Use,""!=DEXT5.config.UserTableLock.LockName&&(a.userTableLock.lockName=DEXT5.config.UserTableLock.LockName.split(",")),""!=DEXT5.config.UserTableLock.DefaultTableLockMode&&(a.userTableLock.defaultTableLockMode=DEXT5.config.UserTableLock.DefaultTableLockMode),""!=DEXT5.config.UserTableLock.DefaultShowLockIcon&&(a.userTableLock.defaultShowLockIcon=DEXT5.config.UserTableLock.DefaultShowLockIcon);
else{var Pa=DEXT5.util.xml.getNodeValue(d,"table_lock_user_mode");if("1"==Pa){a.userTableLock.use=Pa;var y=DEXT5.util.xml.getNode(d,"table_lock_user_mode");y&&y.getAttribute("lock_name")&&""!=y.getAttribute("lock_name")&&(a.userTableLock.lockName=y.getAttribute("lock_name").split(","));y&&y.getAttribute("default_table_lock_mode")&&""!=y.getAttribute("default_table_lock_mode")&&(a.userTableLock.defaultTableLockMode=y.getAttribute("default_table_lock_mode"));y&&y.getAttribute("default_show_lock_icon")&&
""!=y.getAttribute("default_show_lock_icon")&&(a.userTableLock.defaultShowLockIcon=y.getAttribute("default_show_lock_icon"))}}var J=DEXT5.util.xml.getNode(d,"open_document");if(J){J.getAttribute("before_open_event")&&""!=J.getAttribute("before_open_event")&&(a.openDocument.beforeOpenEvent=J.getAttribute("before_open_event"));var Q=DEXT5.util.xml.getNode(J,"word");Q&&(Q.getAttribute("max_size")&&""!=Q.getAttribute("max_size")&&(a.openDocument.word.maxSize=parseInt(Q.getAttribute("max_size"),0)),Q.getAttribute("max_page")&&
""!=Q.getAttribute("max_page")&&(a.openDocument.word.maxPage=parseInt(Q.getAttribute("max_page"),0)));var R=DEXT5.util.xml.getNode(J,"excel");R&&(R.getAttribute("max_size")&&""!=R.getAttribute("max_size")&&(a.openDocument.excel.maxSize=parseInt(R.getAttribute("max_size"),0)),R.getAttribute("max_sheet")&&""!=R.getAttribute("max_sheet")&&(a.openDocument.excel.maxSheet=parseInt(R.getAttribute("max_sheet"),0)));var S=DEXT5.util.xml.getNode(J,"powerpoint");S&&(S.getAttribute("max_size")&&""!=S.getAttribute("max_size")&&
(a.openDocument.powerpoint.maxSize=parseInt(S.getAttribute("max_size"),0)),S.getAttribute("max_slide")&&""!=S.getAttribute("max_slide")&&(a.openDocument.powerpoint.maxSlide=parseInt(S.getAttribute("max_slide"),0)));var Qa=J.getAttribute("use_hwp");Qa&&"1"==Qa&&(a.openDocument.useHwp="1")}"1"==DEXT5.util.xml.getNodeValue(d,"remove_last_br_tag")&&(a.removeLastBrTag="1");""!=DEXT5.config.EditorBodyEditable?"0"==DEXT5.config.EditorBodyEditable&&(a.editorBodyEditable=!1):"0"==DEXT5.util.xml.getNodeValue(d,
"editor_body_editable")&&(a.editorBodyEditable=!1);if(""!=DEXT5.config.ReplaceOutsideImage)a.replaceOutsideImage.use=DEXT5.config.ReplaceOutsideImage,""!=DEXT5.config.ReplaceOutsideImageExceptDomain&&(a.replaceOutsideImage.exceptDomain=DEXT5.config.ReplaceOutsideImageExceptDomain.split(","));else if("1"==DEXT5.util.xml.getNodeValue(d,"replace_outside_image")){a.replaceOutsideImage.use="1";var qa=DEXT5.util.xml.getNode(d,"replace_outside_image");qa.getAttribute("except_domain")&&""!=qa.getAttribute("except_domain")&&
(a.replaceOutsideImage.exceptDomain=qa.getAttribute("except_domain").split(","))}if(""!=DEXT5.config.RemoveComment)a.removeComment=DEXT5.config.RemoveComment;else{var Ra=DEXT5.util.xml.getNodeValue(d,"remove_comment");"0"==Ra&&(a.removeComment=Ra)}if(""!=DEXT5.config.SetDefaultValueInEmptyTag)a.setDefaultValueInEmptyTag=DEXT5.config.SetDefaultValueInEmptyTag.split(",");else{var Sa=DEXT5.util.xml.getNodeValue(d,"set_default_value_in_empty_tag");""!=Sa&&(a.setDefaultValueInEmptyTag=Sa.split(","))}""!=
DEXT5.config.PhotoEditorId&&(a.photoEditorId=DEXT5.config.PhotoEditorId);var u=DEXT5.util.xml.getNode(e,"uploader_setting"),K=DEXT5.util.xml.getNodeValue(u,"develop_langage"),D=DEXT5.util.xml.getNodeValue(u,"handler_url"),Ta=DEXT5.util.xml.getNodeValue(u,"to_save_path_url"),Ua=DEXT5.util.xml.getNodeValue(u,"to_save_file_path_url"),L=DEXT5.util.xml.getNodeValue(u,"save_foldername_rule"),M=DEXT5.util.xml.getNodeValue(u,"save_file_foldername_rule"),Qb=DEXT5.util.xml.getNodeValue(u,"server_domain"),ra=
DEXT5.util.xml.getNodeValue(u,"save_filename_rule"),Rb=DEXT5.util.xml.getNodeValue(u,"image_convert_format"),Sb=DEXT5.util.xml.getNodeValue(u,"image_convert_width"),Tb=DEXT5.util.xml.getNodeValue(u,"image_convert_height"),Ub=DEXT5.util.xml.getNodeValue(u,"image_auto_fit"),Va=DEXT5.util.xml.getNodeValue(u,"handler_url_save_for_notes");""!=DEXT5.config.HandlerUrlSaveForNotes?a.post_url_save_for_notes=DEXT5.config.HandlerUrlSaveForNotes:""!=Va&&(a.post_url_save_for_notes=Va);var da=DEXT5.util.xml.getNode(e,
"extra_setting");da&&(a.paste_image_base64=DEXT5.util.xml.getNodeValue(da,"paste_image_base64"),a.empty_tag_remove=DEXT5.util.xml.getNodeValue(da,"empty_tag_remove"),a.custom_code=DEXT5.util.xml.getNodeValue(da,"custom_code"),DEXT5.config.CustomCode=a.custom_code);a.serverDomain=Qb;0<DEXT5.config.ServerDomain.length&&(a.serverDomain=DEXT5.config.ServerDomain);0<DEXT5.config.HandlerUrl.length&&(D=DEXT5.config.HandlerUrl);a.image_convert_format=Rb;a.image_convert_width=Sb;a.image_convert_height=Tb;
a.image_auto_fit=Ub;var Wa=DEXT5.util.xml.getNodeValue(u,"allow_media_file_type");if(0<Wa.length)for(var Xa=Wa.split(","),Vb=Xa.length,n=0;n<Vb;n++)a.allowMediaFileType.push(Xa[n]);else a.allowMediaFileType=["wmv","asf"];var Ya=DEXT5.util.xml.getNodeValue(u,"allow_image_file_type");if(0<Ya.length)for(var Za=Ya.split(","),Wb=Za.length,n=0;n<Wb;n++)a.allowImageFileType.push(Za[n]);else a.allowImageFileType=["jpg","jpeg","png","gif","bmp"];var $a=DEXT5.util.xml.getNodeValue(u,"allow_flash_file_type");
if(0<$a.length)for(var ab=$a.split(","),Xb=ab.length,n=0;n<Xb;n++)a.allowFlashFileType.push(ab[n]);else a.allowFlashFileType=["swf"];var bb=DEXT5.util.xml.getNodeValue(u,"allow_insert_file_type");if(0<bb.length)for(var cb=bb.split(","),Yb=cb.length,n=0;n<Yb;n++)a.allowInsertFileType.push(cb[n]);else a.allowInsertFileType="txt doc docx xls xlsx ppt pptx hwp pdf".split(" ");"0"==DEXT5.util.xml.getNodeValue(u,"attach_file_image")&&(a.attachFileImage="0");var N=DEXT5.util.xml.getNode(d,"file_delimiter");
""!=DEXT5.config.UnitDelimiter?a.unitDelimiter=String.fromCharCode(DEXT5.config.UnitDelimiter):N&&N.getAttribute("unit_delimiter")&&""!=N.getAttribute("unit_delimiter")&&(a.unitDelimiter=String.fromCharCode(N.getAttribute("unit_delimiter")));""!=DEXT5.config.UnitDelimiter?a.unitAttributeDelimiter=String.fromCharCode(DEXT5.config.UnitAttributeDelimiter):N&&N.getAttribute("unit_attribute_delimiter")&&""!=N.getAttribute("unit_attribute_delimiter")&&(a.unitAttributeDelimiter=String.fromCharCode(N.getAttribute("unit_attribute_delimiter")));
var sa=DEXT5.util.xml.getNode(d,"inoutdent");sa&&sa.getAttribute("default_size")&&(a.inoutdentDefaultSize=sa.getAttribute("default_size"));var p=DEXT5.util.xml.getNode(d,"table_property");p&&(p.getAttribute("width")&&""!=p.getAttribute("width")&&(a.tableDefaultWidth=p.getAttribute("width")),p.getAttribute("height")&&""!=p.getAttribute("height")&&(a.tableDefaultHeight=p.getAttribute("height")),p.getAttribute("class")&&""!=p.getAttribute("class")&&(a.tableDefaultClass=p.getAttribute("class")),p.getAttribute("inoutdent")&&
""!=p.getAttribute("inoutdent")&&(a.tableDefaultInoutdent=p.getAttribute("inoutdent")),p.getAttribute("init_inoutdent")&&""!=p.getAttribute("init_inoutdent")&&(a.tableInitInoutdent=p.getAttribute("init_inoutdent")),p.getAttribute("td_height")&&""!=p.getAttribute("td_height")&&(a.tableDefaultTdHeight=p.getAttribute("td_height")),p.getAttribute("row_max_count")&&""!=p.getAttribute("row_max_count")&&(a.tableRowMaxCount=p.getAttribute("row_max_count")),p.getAttribute("col_max_count")&&""!=p.getAttribute("col_max_count")&&
(a.tableColMaxCount=p.getAttribute("col_max_count")),p.getAttribute("allow_inoutdent_text")&&""!=p.getAttribute("allow_inoutdent_text")&&(a.allowInoutdentText=p.getAttribute("allow_inoutdent_text")),p.getAttribute("default_border_color")&&""!=p.getAttribute("default_border_color")&&(a.defaultBorderColor=p.getAttribute("default_border_color")));var db=DEXT5.util.xml.getNodeValue(p,"class_list");if(0<db.length)for(var eb=db.split(","),Zb=eb.length,n=0;n<Zb;n++)a.tableClassList.push(eb[n]);var fb=DEXT5.util.xml.getNodeValue(p,
"show_line_for_border_none");"0"!=fb&&(a.showLineForBorderNone=fb);var gb=DEXT5.util.xml.getNodeValue(p,"line_style");if(0<gb.length)for(var hb=gb.split(","),$b=hb.length,n=0;n<$b;n++)a.tableLineStyleList.push(hb[n]);var ta=DEXT5.util.xml.getNode(d,"hyperlink_property"),ib=DEXT5.util.xml.getNodeValue(ta,"target");if(0<ib.length)for(var jb=ib.split(","),ac=jb.length,n=0;n<ac;n++)a.hyperlinkTargetList.push(jb[n]);var kb=DEXT5.util.xml.getNodeValue(ta,"category");if(0<kb.length)for(var lb=kb.split(","),
bc=lb.length,n=0;n<bc;n++)a.hyperlinkCategoryList.push(lb[n]);var mb=DEXT5.util.xml.getNodeValue(ta,"protocol");if(0<mb.length)for(var nb=mb.split(","),cc=nb.length,n=0;n<cc;n++)a.hyperlinkProtocolList.push(nb[n]);var ob=DEXT5.util.xml.getNodeValue(p,"no_resize_class");0<ob.length&&(a.tableNoResizeClass=ob);var pb=DEXT5.util.xml.getNodeValue(p,"no_selection_class");0<pb.length&&(a.tableNoSelectionClass=pb);var qb=DEXT5.util.xml.getNodeValue(p,"no_action_class");0<qb.length&&(a.tableNoActionClass=
qb);var W=DEXT5.util.xml.getNode(d,"img_default_size");W&&W.getAttribute("width")&&(a.imgDefaultWidth=W.getAttribute("width"));W&&W.getAttribute("height")&&(a.imgDefaultHeight=W.getAttribute("height"));var G=DEXT5.util.xml.getNode(d,"img_default_margin");G&&(G.getAttribute("margin_left")&&(a.imgDefaultMarginLeft=G.getAttribute("margin_left")),G.getAttribute("margin_right")&&(a.imgDefaultMarginRight=G.getAttribute("margin_right")),G.getAttribute("margin_top")&&(a.imgDefaultMarginTop=G.getAttribute("margin_top")),
G.getAttribute("margin_bottom")&&(a.imgDefaultMarginBottom=G.getAttribute("margin_bottom")));a.style.width=""==DEXT5.config.Width?0==l.length?a.style.width:l:DEXT5.config.Width;a.style.height=""==DEXT5.config.Height?0==q.length?a.style.height:q:DEXT5.config.Height;a.style.skinName=""==DEXT5.config.SkinName?0==r.length?a.style.skinName:r:DEXT5.config.SkinName;if("random"==a.style.skinName){var dc=Math.floor(11*Math.random()),ec=DEXT5.util.getSkinNames();a.style.skinName=ec[dc]}a.defaultMessage=""==
DEXT5.config.DefaultMessage?"":DEXT5.config.DefaultMessage;a.firstLoadType=""==DEXT5.config.FirstLoadType?"":DEXT5.config.FirstLoadType;a.firstLoadMessage=""==DEXT5.config.FirstLoadMessage?"":DEXT5.config.FirstLoadMessage;a.fileFieldID=""==DEXT5.config.FileFieldID?"Filedata":DEXT5.config.FileFieldID;a.nextTabElementId=""==DEXT5.config.NextTabElementId?"":DEXT5.config.NextTabElementId;a.userFieldID=""==DEXT5.config.UserFieldID?"Userdata":DEXT5.config.UserFieldID;a.userFieldValue=DEXT5.config.UserFieldValue;
a.toSavePathURL=""==DEXT5.config.ToSavePathURL?0==Ta.length?a.toSavePathURL:Ta:DEXT5.config.ToSavePathURL;a.toSaveFilePathURL=""==DEXT5.config.ToSaveFilePathURL?0==Ua.length?a.toSaveFilePathURL:Ua:DEXT5.config.ToSaveFilePathURL;a.sourceViewtype="1"==B||"2"==B?B:"0";5<H.length&&"http"==H.substring(0,4).toLowerCase()?(a.userCssUrl=H,ia&&ia.getAttribute("always_set")&&(a.userCssAlwaysSet=ia.getAttribute("always_set"))):a.userCssUrl="";5<T.length&&"http"==T.substring(0,4).toLowerCase()?a.userJsUrl=T:
a.userJsUrl="";a.xhtml_value="1"==U?"1":"0";""!=X&&(a.system_title="0"==X?"":X);if(""!=DEXT5.config.ViewModeAutoHeight)a.view_mode_auto_height=DEXT5.config.ViewModeAutoHeight;else{var rb=DEXT5.util.xml.getNodeValue(d,"view_mode_auto_height");""!=rb&&(a.view_mode_auto_height=rb)}if(""!=DEXT5.config.ViewModeAutoWidth)a.view_mode_auto_width=DEXT5.config.ViewModeAutoWidth;else{var sb=DEXT5.util.xml.getNodeValue(d,"view_mode_auto_width");""!=sb&&(a.view_mode_auto_width=sb)}""!=DEXT5.config.ChangeMultiValueMode&&
(a.changeMultiValueMode=DEXT5.config.ChangeMultiValueMode);"0"==Aa&&(a.tableAutoAdjust="0");var tb=DEXT5.util.xml.getNodeValue(d,"allow_link_media_caption");"1"==DEXT5.config.AllowLinkMediaCaption?a.allowLinkMediaCaption=DEXT5.config.AllowLinkMediaCaption:"1"==tb&&(a.allowLinkMediaCaption=tb);var ua=DEXT5.util.xml.getNodeValue(d,"user_help_url");""!=DEXT5.config.UserHelpUrl&&"http"==DEXT5.config.UserHelpUrl.substring(0,4).toLowerCase()?a.userHelpUrl=DEXT5.config.UserHelpUrl:ua&&"http"==ua.substring(0,
4).toLowerCase()&&(a.userHelpUrl=ua);""!=a.userHelpUrl&&("/"!=a.userHelpUrl.substring(a.userHelpUrl.length-1,a.userHelpUrl.length)&&(a.userHelpUrl+="/"),a.webPath.help=a.userHelpUrl);0<DEXT5.config.mimeCharset.length&&(a.mimeCharset=DEXT5.config.mimeCharset);0<DEXT5.config.mimeConentEncodingType.length&&(a.mimeConentEncodingType=DEXT5.config.mimeConentEncodingType);0<DEXT5.config.mimeLocalOnly.length&&(a.mimeLocalOnly=DEXT5.config.mimeLocalOnly);0<DEXT5.config.mimeRemoveHeader.length&&(a.mimeRemoveHeader=
DEXT5.config.mimeRemoveHeader);0<DEXT5.config.mimeFileTypeFilter.length&&(a.mimeFileTypeFilter=DEXT5.config.mimeFileTypeFilter);0<DEXT5.config.userOpenDlgTitle.length&&(a.userOpenDlgTitle=DEXT5.config.userOpenDlgTitle);0<DEXT5.config.userOpenDlgType.length&&(a.userOpenDlgType=DEXT5.config.userOpenDlgType);0<DEXT5.config.userOpenDlgInitDir.length&&(a.userOpenDlgInitDir=DEXT5.config.userOpenDlgInitDir);0<DEXT5.config.userImageDlgStyle.length&&(a.userImageDlgStyle=DEXT5.config.userImageDlgStyle);0<DEXT5.config.mimeBaseURL.length&&
(a.mimeBaseURL=DEXT5.config.mimeBaseURL);""!=DEXT5.config.ShowDialogPosition?a.showDialogPosition=DEXT5.config.ShowDialogPosition:""!=x&&(a.showDialogPosition=x);""!=DEXT5.config.StatusBarItem&&(a.statusBarItem=DEXT5.config.StatusBarItem);t=t.toLowerCase();a.lang=""==t?"ko-kr":DEXT5.util.getUserLang(t);2<=DEXT5.config.InitLang.length&&(a.lang=DEXT5.util.getUserLang(DEXT5.config.InitLang));2<=DEXT5.config.Lang.length&&(a.lang=DEXT5.util.getUserLang(DEXT5.config.Lang));a.accessibility=0==A.length?"0":
A;var va=DEXT5.util.xml.getNode(d,"accessibility");""==DEXT5.config.AccessibilityValidationItems?va&&va.getAttribute("validation_item")&&(a.accessibilityValidationItems=va.getAttribute("validation_item")):a.accessibilityValidationItems=DEXT5.config.AccessibilityValidationItems;if(""!=DEXT5.config.SaveFolderNameRule)a.saveFolderNameRule=DEXT5.config.SaveFolderNameRule;else if("YYYYMMDD/"==L||"YYYYMM/"==L||"YYYY/"==L||"YYYY/MM/"==L||"YYYY/MM/DD/"==L||"/"==L||""==L)a.saveFolderNameRule=L;if(""!=DEXT5.config.SaveFileFolderNameRule)a.saveFileFolderNameRule=
DEXT5.config.SaveFileFolderNameRule;else if("YYYYMMDD/"==M||"YYYYMM/"==M||"YYYY/"==M||"YYYY/MM/"==M||"YYYY/MM/DD/"==M||"/"==M||""==M)a.saveFileFolderNameRule=M;if("GUID"==ra||"DATETIME"==ra)a.saveFileNameRule=ra;var ub=DEXT5.util.xml.getNodeValue(d,"topmenu"),Z=DEXT5.util.xml.getNodeValue(d,"toolbar"),vb=DEXT5.util.xml.getNodeValue(d,"toolbaradmin"),wb=DEXT5.util.xml.getNodeValue(d,"topstatusbar"),xb=DEXT5.util.xml.getNodeValue(d,"statusbar"),yb=DEXT5.util.xml.getNodeValue(d,"resizebar");a.top_menu=
"1"==ub?ub:"0";a.tool_bar="1"==Z||"2"==Z||"3"==Z||"4"==Z?Z:"0";if(""!=DEXT5.config.ToolBarGrouping)a.tool_bar_grouping=DEXT5.config.ToolBarGrouping;else{var ea=DEXT5.util.xml.getNode(d,"toolbar");ea&&ea.getAttribute("grouping")&&""!=ea.getAttribute("grouping")&&(a.tool_bar_grouping=ea.getAttribute("grouping"))}a.top_status_bar=""!=wb?wb:"1";a.status_bar="1"==xb?xb:"0";a.resize_bar="1"==yb?yb:"0";a.tool_bar_admin="1"==vb?vb:"0";""!=DEXT5.config.zTopMenu&&(a.top_menu=DEXT5.config.zTopMenu);""!=DEXT5.config.zToolBar&&
(a.tool_bar=DEXT5.config.zToolBar);""!=DEXT5.config.zTopStatusBar&&(a.top_status_bar=DEXT5.config.zTopStatusBar);""!=DEXT5.config.zStatusBar&&(a.status_bar=DEXT5.config.zStatusBar);if(""!=DEXT5.config.StatusBarLoading)a.statusBarLoading=DEXT5.config.StatusBarLoading;else{var fa=DEXT5.util.xml.getNode(d,"statusbar");fa&&fa.getAttribute("loading")&&""!=fa.getAttribute("loading")&&(a.statusBarLoading=fa.getAttribute("loading"))}if(""!=DEXT5.config.TopStatusBarLoading)a.topStatusBarLoading=DEXT5.config.TopStatusBarLoading;
else{var ga=DEXT5.util.xml.getNode(d,"topstatusbar");ga&&ga.getAttribute("loading")&&""!=ga.getAttribute("loading")&&(a.topStatusBarLoading=ga.getAttribute("loading"))}""!=DEXT5.config.HasContainer&&(a.hasContainer=DEXT5.config.HasContainer);""!=DEXT5.config.Mode?a.mode=DEXT5.config.Mode:"view"==DEXT5.util.xml.getNodeValue(d,"default_mode")&&(a.mode="view");var aa="",aa=0==D.length?DEXT5.rootPath:"/"==D.substring(0,1)?location.protocol+"//"+location.host:4<D.length&&"http"==D.substring(0,4).toLowerCase()?
"":DEXT5.rootPath;a.style.InitVisible=DEXT5.config.InitVisible;""!=DEXT5.config.DevelopLangage?a.developLang=DEXT5.config.DevelopLangage:0<K.length&&(a.developLang=K);if("user"!=a.developLang.toLowerCase())if(""!=DEXT5.config.Security.EncryptParam)a.security.encryptParam="1"==DEXT5.config.Security.EncryptParam?"1":"0";else{var zb=DEXT5.util.xml.getNode(d,"security");if(zb){var fc=DEXT5.util.xml.getNodeValue(zb,"encrypt_param");a.security.encryptParam="1"==fc?"1":"0"}}var wa=!1;if(DEXT5.isRelease&&
("1"==DEXT5.config.UseGZip?wa=!0:"1"==DEXT5.util.xml.getNodeValue(d,"use_gzip")&&(wa=!0),1==wa))switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.editor_url=DEXT5.rootPath+"pages/editor_release_java.html";break;case "PHP":a.editor_url=DEXT5.rootPath+"pages/editor_release_php.html";break;default:a.editor_url=DEXT5.rootPath+"pages/editor_release_net.html"}if(0==D.length)switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.post_url=aa+"handler/upload_handler.jsp";break;case "PHP":a.post_url=
aa+"handler/upload_handler.php";break;default:a.post_url=aa+"handler/upload_handler.ashx"}else{if(4<D.length&&"http"==D.substring(0,4).toLowerCase()&&D.match(/:\/\/(.[^\/]+)/)[1]!=window.location.host){var ha="";switch(K.toUpperCase()){case "JAVA":case "JSP":ha=DEXT5.rootPath+"handler/upload_handler.jsp";break;case "PHP":ha=DEXT5.rootPath+"handler/upload_handler.php";break;default:ha=DEXT5.rootPath+"handler/upload_handler.ashx"}a.proxy_url=ha}a.post_url=aa+D}""!=a.userFieldValue&&(-1<a.post_url.indexOf("?")?
a.post_url=a.post_url+"&"+a.userFieldID+"="+a.userFieldValue:a.post_url=a.post_url+"?"+a.userFieldID+"="+a.userFieldValue);""!=DEXT5.config.focusInitObjId&&(a.focusInitObjId=DEXT5.config.focusInitObjId);""!=DEXT5.config.focusInitEditorObjId&&(a.focusInitEditorObjId=DEXT5.config.focusInitEditorObjId);""!=DEXT5.config.tabIndexObjId&&(a.tabIndexObjId=DEXT5.config.tabIndexObjId);""!=DEXT5.config.SetValueObjId&&(a.setValueObjId=DEXT5.config.SetValueObjId);""!=DEXT5.config.LoadedEvent&&(a.LoadedEvent=DEXT5.config.LoadedEvent);
""!=DEXT5.config.DirectEditHtmlUrl&&(a.directEditHtmlUrl=DEXT5.config.DirectEditHtmlUrl);var z=DEXT5.util.xml.getNode(e,"license"),gc=DEXT5.util.xml.getNodeValue(z,"product_key"),Ab=DEXT5.util.xml.getNodeValue(z,"license_plugin"),Bb=DEXT5.util.xml.getNodeValue(z,"plugin_use"),Cb=DEXT5.util.xml.getNodeValue(z,"image_editor_use"),xa=DEXT5.util.xml.getNodeValue(z,"plugin_version"),hc=DEXT5.util.xml.getNodeValue(z,"print_preview"),Db=DEXT5.util.xml.getNodeValue(z,"print_header"),Eb=DEXT5.util.xml.getNodeValue(z,
"print_footer"),ya=DEXT5.util.xml.getNode(z,"mime_use"),Fb=DEXT5.util.xml.getNodeValue(z,"mime_use"),ic=DEXT5.util.xml.getNodeValue(z,"trust_sites");a.LicenseKey=""!=DEXT5.config.LicenseKey?DEXT5.config.LicenseKey:DEXT5.util.xml.getNodeValue(z,"license_key");a.printPreview="1"==hc?"1":"0";a.printHeader=Db;a.printFooter=Eb;a.basePrintHeader=Db;a.basePrintFooter=Eb;a.trustSites=ic;a.productKey=""!=DEXT5.config.ProductKey?DEXT5.config.ProductKey:gc;""!=Ab&&(a.plugin_root=Ab);a.plugInUse=""==DEXT5.config.pluginUse?
0==Bb.length?a.plugInUse:Bb:DEXT5.config.pluginUse;0==a.plugInUse&&"ieplugin"==a.runtimes&&(a.plugInUse=1);a.imageEditorUse=""==DEXT5.config.imageEditorUse?0==Cb.length?a.imageEditorUse:Cb:DEXT5.config.imageEditorUse;""==DEXT5.config.mimeCharset?ya&&ya.getAttribute("mimeCharset")&&(a.mimeCharset=ya.getAttribute("mimeCharset")):a.mimeCharset=DEXT5.config.mimeCharset;a.mimeUse=""==DEXT5.config.mimeUse?0==Fb.length?a.mimeUse:Fb:DEXT5.config.mimeUse;null!=xa&&7<=xa.length&&(a.plugin_version=xa);if(""==
a.proxy_url&&("NET"==K.toUpperCase()||"JSP"==K.toUpperCase()||"JAVA"==K.toUpperCase()||"PHP"==K.toUpperCase()||"ASP"==K.toUpperCase())){var ba=a.post_url;""!=a.userFieldValue&&(ba=a.post_url.split("?")[0]);var O=DEXT5.ajax.load(ba+"?dext=test");"CCODE_001"==a.custom_code&&(O=DEXT5.ajax.load(ba+"?hello=test"));if(null==O||""==O){var C="",za=0<DEXT5.config.InitXml.length?za:"dext_editor.xml";"ko"==a.lang||"ko-kr"==a.lang?(C="Editor\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n",
C+=ba+"\n\n",C+=za+" \ud30c\uc77c\uc758 uploader_setting \uc139\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):(C="Editor's setting is not correct. Access the following URL is not valid.\n\n",C+=ba+"\n\n",C+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" section in the "'+za+'."');alert(C);return}O=O.toLowerCase();-1<O.indexOf("hi, dext5 editor !!!!")&&-1<O.indexOf("-")&&(DEXT5.ServerReleaseVer=O.split("-")[1])}a.useLog=
"1"==DEXT5.config.useLog?"1":"0";this.editor=null;a.editor_id=b;this.FrameID="dext_frame_"+b;a.holderID="dext_frame_holder"+b;this.ID=b;var P="",Gb=a.style.height;0==a.style.InitVisible&&(Gb="1px");P='<div id="'+a.holderID+'" style="width:'+a.style.width+"; height:"+Gb+"; ";if(DEXT5.browser.iOS||DEXT5.browser.mobile)P+=" overflow:scroll; overflow-x:hidden; -webkit-overflow-scrolling:touch; ";P+='"></div>';if(""!=DEXT5.config.EditorHolder){var Hb=document.getElementById(DEXT5.config.EditorHolder);
Hb?Hb.innerHTML=P:document.write(P)}else document.write(P);var jc=document.getElementById(a.holderID),v;try{v=document.createElement("<iframe frameborder='0' scrolling='no'>")}catch(lc){v=document.createElement("iframe"),v.setAttribute("frameborder","0"),v.setAttribute("scrolling","no")}v.setAttribute("id",this.FrameID);v.style.width="100%";v.style.height="100%";a.style.height.indexOf("%");if(DEXT5.browser.iOS||DEXT5.browser.mobile)v.style.overflow="hidden",v.style.display="inline-block";v.width=
"100%";v.height="100%";jc.appendChild(v);var kc=this,Ib=function(){try{v.contentWindow.dext_frame_loaded_event(b,a,kc)}catch(c){""!=DEXT5.config.LoadErrorCustomMessage?alert(DEXT5.config.LoadErrorCustomMessage):alert("ErrCode : 1001")}};v.addEventListener?v.addEventListener("load",Ib,!1):v.attachEvent&&v.attachEvent("onload",Ib);v.src=a.editor_url;""!=a.custom_code&&DEXT5.util.CustomSetting("function",a.custom_code,a)}}}
function CustomSettingFunction(b){"CCODE_001"==b.custom_code&&(b.empty_tag_remove="1",b.sourceViewtype="1",b.system_title="",b.tableAutoAdjust="0",b.accessibility="-1",b.tool_bar="2",b.top_menu="1",b.setDefaultStyle.value="2",b.setDefaultStyle.body_id="hello_body",b.emoticon_url=DEXT5.rootPath+"config/hello_emoticon.xml",b.forms_url=DEXT5.rootPath+"config/hello_formlist.xml")}
function CustomRemoveItem(b){var c=[];"CCODE_001"==b&&(c="save pagebreak copy cut paste doc_bg_image insert_link_media media_create entity iframe_create flash_create table_row_clone about insert_row_column grid tool_replace convert_table_to_text table_tool table_indent table_outdent row_property column_property align_vertical".split(" "));return c}
function replacePtOrCmToPx(b){try{for(var c=b.toLowerCase().split(" "),a=c.length,e,g,k="",f=0;f<a;f++){var h=c[f];-1<h.indexOf("pt")?(e=4*parseFloat(h)/3,0<e&&1>e&&(e=1),0>e&&(e=0),g=Math.round(e)+"px",k=""!=k?k+" "+g:g):-1<h.indexOf("cm")?(_cm=37.795275593333*parseFloat(h),0<_cm&&1>_cm&&(_cm=1),0>_cm&&(_cm=0),g=Math.round(_cm)+"px",k=""!=k?k+" "+g:g):k=""!=k?k+" "+h:h}return""!=k?k:b}catch(d){return b}}window.DEXT5&&"samsung.net"==document.domain&&(window.HELLO=window.DEXT5,HelloEditor=Dext5editor);
function GetUserRunTimeEditor(b){b=b.toLowerCase();var c="";""==b||"html5"==b?c="html5":"ieplugin"==b?c=1==DEXT5.browser.ie&&12>DEXT5.browser.ieVersion?"ieplugin":"html5":-1<b.indexOf("ieplugin")&&8<b.length?(b=DEXT5.util.parseIntOr0(b),c=1==DEXT5.browser.ie&&b>=DEXT5.browser.ieVersion?"ieplugin":"html5"):c="html5";return c};
